build_search_index = true
compile_sass = true
default_language = "en"
description = "eloquent geek games blog"
taxonomies = [
    {name = "categories", rss = false},
    {name = "tags", rss = false},
]
theme = "eg-blog-theme"
title = "eloquent blog"

[markdown]
highlight_code = true
render_emoji = true

[search]
include_title = true
include_description = false
include_content = false

[extra]
eg_author = "basie"

# Path references static/images
eg_icon = "/images/logo.png"

eg_iconsize = 70

# May not need these?
# eg_dark_mode = true
# eg_favicon = "/images/favicon.png"
# eg_indexposts = 5
# eg_theme_toggler = true
