name = "eg-blog-theme"
description = "eg's theme for blogging with. Duh."
license = "UNLICENSED"
min_version = "0.14.1"
homepage = "https://github.com/richchurcher/eg-blog-theme"
demo = ""

[author]
homepage = "https://github.com/eloquentgeek"
name = "Basie"
